repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-json
- repo: git://github.com/doublify/pre-commit-clang-format
  rev: master
  hooks:
    - id: clang-format
