repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-yaml
      exclude: "^backend/charts/[^/]*/templates"
    - id: check-json
- repo: https://github.com/pocc/pre-commit-hooks
  rev: python
  hooks:
    - id: clang-format
      args: [--style=Google, -i]
