apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 192.168.2.185
      user: vagrant
      port: 22
      keyPath: /home/paulcollins/coding/iot-boards/backend/kubernetes/.vagrant/machines/default/virtualbox/private_key
    role: controller+worker
  k0s:
    version: "0.13.0"
    config:
      spec:
        extensions:
          helm:
            repositories:
            - name: traefik
              url: https://helm.traefik.io/traefik
            - name: bitnami
              url: https://charts.bitnami.com/bitnami
            - name: jetstack
              url: https://charts.jetstack.io
            charts:
              - name: traefik
                chartname: traefik/traefik
                version: "9.11.0"
                namespace: default
                values: |2
                  providers:
                    kubernetesIngress:
                      enabled: true
                  ports:
                    mqtt:
                      port: 1883
                      protocol: TCP
                      expose: true
                      exposedPort: 1883
                    docker:
                      port: 5000
                      protocol: TCP
                      expose: true
                      exposedPort: 5000
              - name: metallb
                chartname: bitnami/metallb
                version: "1.0.1"
                namespace: default
                values: |2
                  configInline:
                    address-pools:
                    - name: generic-cluster-pool
                      protocol: layer2
                      addresses:
                      - 192.168.2.30-192.168.2.35
              - name: cert-manager
                chartname: jetstack/cert-manager
                version: "v1.3.0"
                namespace: cert-manager
                values: |2
                  installCRDs: true
