apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 192.168.2.207
      user: vagrant
      port: 22
    role: controller+worker
  k0s:
    version: 1.22.4+k0s.1
    config:
      spec:
        extensions:
          helm:
            repositories:
            - name: bitnami
              url: https://charts.bitnami.com/bitnami
            - name: jetstack
              url: https://charts.jetstack.io
            charts:
              - name: metallb
                chartname: bitnami/metallb
                version: "2.6.2"
                namespace: default
                values: |2
                  configInline:
                    address-pools:
                    - name: generic-cluster-pool
                      protocol: layer2
                      addresses:
                      - 192.168.2.30-192.168.2.35
              - name: cert-manager
                chartname: jetstack/cert-manager
                version: "v1.6.1"
                namespace: cert-manager
                values: |2
                  installCRDs: true
              - name: external-dns
                chartname: bitnami/external-dns
                version: "6.1.2"
                namespace: default
                values: |2
                  policy: sync
                  rbac:
                    create: true
                  provider: rfc2136
                  rfc2136:
                    host: "192.168.2.1"
                    port: 53530
                    zone: "kaffi.home"
                    tsigSecretAlg: hmac-sha256
                    tsigKeyname: rndc-key
                    secretName: rndc-key
                    minTTL: "2m"
