apiVersion: v1
kind: Service
metadata:
  name: {{ include "kaffi-registry.fullname" . }}
  labels:
    {{- include "kaffi-registry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: registry
  selector:
    {{- include "kaffi-registry.selectorLabels" . | nindent 4 }}
