# Persisten volumes defined for the helm chart
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tsdb-1
  labels:
    type: local
  namespace: iot
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /kubepaths/tsdb-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tsdb-2
  labels:
    type: local
  namespace: iot
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /kubepaths/tsdb-2
