apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescaledb
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      containers:
        - name: timescaledb
          image: timescale/timescaledb:latest-pg12
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            # TODO: THIS MUST BE MOVED TO SECRETS LATER
            - name: POSTGRES_PASSWORD
              value: sekret
