apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eclipse-mqtt.fullname" . }}
data:
  mosquitto: |
    persistent_client_expiration 2h
    listener 1883
    socket_domain ipv4
    log_dest stderr
    log_timestamp true
    log_timestamp_format %Y-%m-%dT%H:%M:%S
    allow_anonymous true
