{{- $defaultSecret := dict "data" (dict "admin-user-password" (randAlphaNum 10 | b64enc | quote) "admin-user-token" (randAlphaNum 20 | b64enc | quote)) -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace .Values.influxdb.auth.existingSecret | default $defaultSecret -}}
{{- $influxAdminPw := index $secret.data "admin-user-password" -}}
{{- $influxAdminToken := index $secret.data "admin-user-token" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.influxdb.auth.existingSecret }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  admin-user-password: {{ $influxAdminPw }}
  admin-user-token: {{ $influxAdminToken }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.telegraf.envFromSecret }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  ADMIN_USER: {{ "admin" | b64enc }}
  ADMIN_PW: {{ $influxAdminPw }}
  ADMIN_TOKEN: {{ $influxAdminToken }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-grafana-datasources
  labels:
    grafana_datasource: ""
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
 influxdatasource.yaml: |-
   apiVersion: 1
   datasources:
    - name: Influx
      type: influxdb
      access: proxy
      url: http://iot-influxdb:8086
      database: primary
      secureJsonData:
        token: {{ $influxAdminToken | b64dec }}
      jsonData:
        version: Flux
        organization: primary
        defaultBucket: primary
